# Load balancing config (round-robin or weighted)
worker_processes  1;

events { worker_connections 1024; }

stream {
    upstream dns_backend {
        # If dns1 fails 3 times within 10 seconds, Nginx temporarily stops sending it traffic.
        # Traffic goes to dns2 until dns1 is considered healthy again.
        server dns1:1053 weight=2 max_fails=3 fail_timeout=10s;
        server dns2:1053 weight=1 max_fails=3 fail_timeout=10s;
        server dns3:1053 weight=1 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 1053 udp;
        proxy_pass dns_backend;
    }
}
